### ISSUE TITLE
Question -- Beep noise at boot of ISO

### ISSUE THREAD

**Issue by ryanmusante** [grml/grml-live#61] opened 2018-09-23 02:06 UTC
There is a very noticeable loud beep when reaching the menu of the ISO. Is there a way to disable this?

**Comment by jkirk** [comment] 2018-09-27 08:49
Are you talking about the beep sound at the end of the boot process? There is a `nobeep` boot option to "disable welcome chime, sounded before grml-quickconfig starts.", see: [Grml Cheatcodes](http://git.grml.org/?p=grml-live.git;a=blob_plain;f=templates/GRML/grml-cheatcodes.txt;hb=HEAD).

Please be aware that **grml-live** is the build system for creating a Grml (based) live system. If you have questions / issues regarding Grml itself, please go to https://github.com/grml/grml/issues

If you have **grml-live** installed and want to customize the ISO to disable the beep sound, you might want to have a look at [`/etc/grml/templates/boot/isolinux/default.cfg`](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/default.cfg).

As this is not a bug in **grml-live** I am closing this issue. If anything is unanswered or unclear please just re-open this issue. Thank you for using Grml!

**Comment by mika** [comment] 2018-09-27 09:00
I think @ryanmusante was refering to the beep of the isolinux splash itself? This is generated by the special '^G' character in line 33 at https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/vesamenu.cfg#L33 (see https://raw.githubusercontent.com/grml/grml-live/master/templates/boot/isolinux/vesamenu.cfg to actually get the character displayed).

I'm not sure what our users expect to have/get WRT to that nowadays, tbh. We no longer put real focus into accessibility for visually impaired users, though sometimes the beep is also nice to have in e.g. the datacenter to be aware once the boot splash and later on the userland prompt is available, while I personally tend to find it more annoying than helpful in general. We also don't seem to have this feature present for e.g. (U)EFI/Secure Boot with GRUB, so maybe it's time to drop this?

Opinions, @jkirk @formorer @zeha @evgeni?

(PS: I think re-opening issues works only for project maintainers)

**Comment by ryanmusante** [comment] 2018-09-27 11:29
@jkirk I'm speaking of the beep immediately preceding the boot menu where you select Addons,Boot OS. It just seems rather abrasive with the kind of speakers I use. I don't mean to label it a bug, just hoping it could be optional rather than default.

**Comment by mika** [comment] 2018-09-27 11:35
@ryanmusante The problem is that it's not possible to make this an optional feature, since there's no way how to control this within isolinux/grub. For sure you can just adjust the according isolinux configuration (either remaster the ISO, or when using e.g. grml2usb/grml2iso adjust the according configuration file directly on the resulting media).

Let's see whether we get rid of this behavior. :)

Also cc-ing @richih while at it - who was one of the proponents of this feature (at least WRT the implementation in userspace that can be controlled via nobeep), IIRC.

**Comment by RichiH** [comment] 2018-09-28 07:20
I can see the value of BIOS-beep, especially in the case of hardware taking a long time to go through initial BOOT, checks, etc.

I am uncertain of how many people with visual impairment still use GRML; as @mika said, it's less of a focus now, so many of those users would probably have drifted away over time.

Overall, I don't feel strongly about beep/no beep any more, but I do strongly believe that if there's a beep, it should happen at any time users should pay attention until they have a working system, no matter the path they take. I.e. having it both after BIOS/UEFI _and_ user space being ready, or in no place at all.

**Comment by jkirk** [comment] 2019-10-23 14:03
I would also vote for keeping the beep (both, after BIOS/UEFI and on grml-quickconfig). Thinking loud here: documenting a way to build a "quiet" Grml ISO would be fine though.

**Comment by mika** [comment] 2019-10-25 08:49
Alright, so let's keep it as-is for the time being.

There's no simple way how to disable the beep at the boot prompt (isolinux/syslinux) of the Grml ISO, though to prevent the beep when booting finished you can use the "nobeep" boot option.
If you want to get rid of the beep in isolinux/syslinux you've to rebuild/remaster the ISO with the beep (see "^G") from `boot/isolinux/vesamenu.cfg`.

Closing hereby

**Comment by verndog** [comment] 2020-06-26 18:25
That piercing speaker sound has GOT to got!!! Its excruciating! This is the only distro that I have ever used that uses the PC speaker. WHY?!

**Comment by mika** [comment] 2020-06-27 08:44
I'm willing to re-open this issue. Personally I think we should indeed consider **disabling** it by default at least in the boot loaders (isolinux/syslinux/grub) and preferably also in the boot-up sequence. If someone wants a beep when booting finished, then an boot option like `beep` should be good enough.

Further opinions? /cc @jkirk @RichiH @formorer @zeha

**Comment by zeha** [comment] 2020-06-27 14:46
Thanks for the new feedback, even if presented in an ungrateful way.

On the feature itself: I believe the beep feature is only ever useful if you have trouble booting - be it either you can’t see the console, typing doesn’t work at some point in the boot stage, or you’re not sure which machine you are looking for in the first place. There are many more such problems, where the beep helps.
If the beep is going to be disabled by default, I think it should be removed completely instead, as it would be a completely dead feature.

**Comment by verndog** [comment] 2020-06-27 14:52
As it is, grml is unusable. That piercing pcspkr sound is intolerable!
I edit grub, added nobeep to the end of the linus line. No different.
I have never heard any pcspkr sound ever from any Linux before.
That pcspkr is used for computer error codes.

Checked the grub mods, I couldn't find pcskpr to rmmod.

**Comment by zeha** [comment] 2020-06-28 17:50
This choice of language and reasoning is unacceptable in this bug tracker.
We can certainly discuss the merits and validity of various usecases, but based on facts and usecases, not based on generic hostility. I'm locking this issue for now.

**Closed** 2022-10-07 04:59 UTC
