### ISSUE TITLE
dhcpcd fails to install with stable flavor

### ISSUE THREAD

**Issue by pasja** [grml/grml-live#138] opened 2023-07-22 19:18 UTC
Dear Colleagues,

Since e7ada958c302e9ca5c2fafffefe265c51723b26e creating a GRML iso with the following command `grml-live -A -V -c GRMLBASE,AMD64,XORG,GRML_FULL -s stable -U pasja -o /home/pasja/grml/` seems to be problematic. 
It fails with this error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dhcpcd-base : Conflicts: dhcp-client
E: Unable to correct problems, you have held broken packages.
ERROR: 25600 25600
```
With the `testing` flavor everything works as expected.

After looking to dhcpcd's debian issues, I think that we hit https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036085 The fix has not had reached stable yet, but it is on its way: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040951 

So this is more of an FYI type of issue :) 

Regards,
János Pásztor

**Comment by mika** [comment] 2023-08-11 17:32
@pasja which grml-live version are you using? Make sure to use latest grml-live >=0.44.0, which uses `--exclude=info,tasksel,tasksel-data,isc-dhcp-client,isc-dhcp-common` within `FAI_DEBOOTSTRAP_OPTS`, otherwise it for sure might end up with problems as you noticed.

Thanks for the pointers WRT https://bugs.debian.org/1036085 + https://bugs.debian.org/1040951!
But I wasn't able to reproduce your issue today (with stable/bookworm), so it's either not an issue thanks to the grml-live version I'm running, or the issue was fixed in bookworm (FYI, I got dhcpcd v9.4.1-22)? :)

**Comment by mika** [comment] 2023-09-08 07:41
I finally managed to reproduce your issue! :) The problem is related to the cloud-init package, which has a hard dependency on isc-dhcp-client, I've reported this towards Debian at https://bugs.debian.org/1051421 - sadly this won't reach bookworm AFAICT.

I don't see a perfect solution for us within grml-live yet. We could either drop `cloud-init` from `GRML_FULL` or moving it to a separate new FAI class file, which then gets enabled only for trixie/testing and newer, though then cloud-init support would be missing on Grml builds based on bookworm. I guess the best option would be to still rely on isc-dhcp-client for bookworm based builds, and use dhcpcd for trixie and newer, which should allow us to ship cloud-init everywhere™.

**Comment by mika** [comment] 2023-09-08 15:42
I think I came up with a workaround to handle this, see https://github.com/grml/grml-live/commit/e530f07e948ce58bec9e019524a147281c25e2e1 which I'll provide through a new grml-live release soonish.

Thanks, @pasja  for reporting this! :+1:

**Closed** 2023-09-08 15:42 UTC
Labels: bug

**Comment by pasja** [comment] 2023-09-10 08:18
Hello @mika

Thanks for pushing this towards resolution! And sorry for disappearing after the report, but real life™ happened. 

Just finished building a fresh ISO with version 0.46, and I can confirm that it works as expected.

Regards,
János Pásztor

**Comment by mika** [comment] 2023-09-14 15:34
@pasja no hurry and worries at all, thanks for testing and confirming, appreciated!
